# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

part_of_kernel <- function(a, b, n) {
    .Call(`_Class783_part_of_kernel`, a, b, n)
}

